apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: MAINFRAME.MQ.STREAMING.QUEUE
  namespace: cp4i
  labels:
    eventstreams.ibm.com/cluster: eventstreams
spec:
  replicas: 1
  partitions: 1
