apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: my-kafka-cluster
  namespace: event-automation
spec:
    kafka:
      storage:
        class: ocs-storagecluster-ceph-rbd
    zookeeper:
      storage:
        class: ocs-storagecluster-ceph-rbd