apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: my-eem-manager
spec:
  license:
    accept: true
    license: L-HRZF-DWHH7A
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    apic:
      jwks:
        endpoint: >-
          https://cpd-cp4i.apps.ocp-2700015rqr-y4lq.cloud.techzone.ibm.com/integration/apis/cp4i/apic-cluster/api/cloud/oauth2/certs
    tls: 
      trustedCertificates:
        - certificate: ca.crt
          secretName: apim-cpd
    authConfig:
      authType: LOCAL
    storage:
      type: persistent-claim
      size: 250M
      storageClassName: PATCHED_BY_KUSTOMIZE
    template:
      pod:
        spec:
          containers:
            - name: manager
              resources:
                requests:
                  cpu: '0.25'
                  memory: 256Mi
                limits:
                  cpu: '0.5'
                  memory: 512Mi
