kind: Secret
apiVersion: v1
metadata:
  annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
  name: my-eem-manager-ibm-eem-user-roles
data:
  user-mapping.json: >-
    ewogICAgIm1hcHBpbmdzIjogWwogICAgICAgIHsKICAgICAgICAgICAgImlkIjogImVlbS1hZG1pbiIsCiAgICAgICAgICAgICJyb2xlcyI6IFsKICAgICAgICAgICAgICAgICJhdXRob3IiCiAgICAgICAgICAgIF0KICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgImlkIjogImVzLXVzZXIiLAogICAgICAgICAgICAicm9sZXMiOiBbCiAgICAgICAgICAgICAgICAidmlld2VyIgogICAgICAgICAgICBdCiAgICAgICAgfQogICAgXQp9
type: Opaque