apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: building-events-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: 4. Building Events
      name: building-events-product
      description: >-
        Kafka Topics for events in the building - includes usage of badges and sensor readings from rooms. 

        Managed by the operations team. 
      version: '1.0'
      categories:
          - Domain/Accounts
          - Protocol/Kafka
    gateways:
       - event-gateway
    plans:
      default-plan:
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: door-badgein-api
      - name: sensor-readings-api
  share:
    apim:
      providerOrg: providerorg
      catalog: sandbox
