kind: ConfigMap
apiVersion: v1
metadata:
  name: singleinstance-qm-configmap
data:
  mq.ini: |
    Channels:
      MaxChannels=200
      MaxActiveChannels=100

  tls.mqsc: |
    DEFINE QLOCAL('MAINFRAME-QUEUE') DEFPSIST(YES) REPLACE 
    
    DEFINE QLOCAL('MAINFRAME-QUEUE-STREAMING') REPLACE
    ALTER QLOCAL('MAINFRAME-QUEUE') STRMQOS(BESTEF) STREAMQ('MAINFRAME-QUEUE-STREAMING')
    
    DEFINE CHANNEL(SICHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) REPLACE
    SET CHLAUTH(SICHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)
