apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: es-cluster-2
spec:
  adminApi: {}
  adminUI:
    authentication:
      - type: scram-sha-512
  license:
    accept: true
    license: L-HRZF-DWHH7A
    use: EventAutomationNonProduction
  requestIbmServices:
    iam: false
    monitoring: false
  strimziOverrides:
    entityOperator:
      topicOperator: {}
      userOperator: {}
    kafka:
      authorization:
        authorizerClass: com.ibm.eventstreams.runas.authorizer.RunAsAuthorizer
        supportsAdminApi: true
        type: custom
      config:
        auto.create.topics.enable: true
      listeners:
        - name: authsslsvc
          authentication:
            type: scram-sha-512
          port: 9095
          tls: true
          type: internal
      replicas: 1
      storage:
        type: persistent-claim
        size: 50Gi
        class: ocs-storagecluster-ceph-rbd
    zookeeper:
      replicas: 1
      storage:
        type: persistent-claim
        size: 3Gi
        class: ocs-storagecluster-ceph-rbd
  version: latest
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: cluster-2-topic
  labels:
    eventstreams.ibm.com/cluster: es-cluster-2
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '1024288000'
  partitions: 3
  replicas: 3
