apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: cat-facts-api
  namespace: cp4i
spec:
  definition:
    external: https://catfact.ninja/docs/api-docs.json
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg

