apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: countries-gql-api
  namespace: cp4i
spec:
  definition:
    configMap: countries-gql-api-definition
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg
