kind: ConfigMap
apiVersion: v1
metadata:
  name: door-badgein-api-definition
  namespace: cp4i
data:
  data: |-
    asyncapi: 2.1.0
    info:
      description: >-
        Records an employee using their id badge to go through a door. This includes
        entry into the building overall, as well as entry through internal office
        doors.
    
    
        Building exits do not require use of id badge, so a door badge in event does
        not imply that the employee will still be in the building.
    
    
        Note that door events can take up to 3 minutes to reach the Kafka topic, so
        the badgetime value in the message payload should be treated as the
        canonical timestamp for the event.
    
    
        This delay can be inconsistent, so messages on the topic are often out of
        sequence as a result.
      title: DOOR.BADGEIN
      version: 1.0.0
      contact:
        email: andre@loosehangers.com
      x-ibm-name: door.badgein
    tags:
      - name: operations
    channels:
      DOOR.BADGEIN:
        bindings:
          kafka:
            partitions: 3
            replicas: 1
        subscribe:
          message:
            payload:
              namespace: com.loosehangerjeans
              type: record
              name: BadgeIn
              fields:
                - name: recordid
                  type: string
                  logicalType: uuid
                  doc: badgeeventid
                - name: door
                  type: string
                  doc: >-
                    Codeforthedoorthatrecordedtheevent.Doorcodesaremadeupofabuildingname,floornumber,anddoornumber,allseparatedbyhyphens(-)
                - name: employee
                  type: string
                  doc: useridassociatedwiththenamebadge
                - name: badgetime
                  type: string
                  doc: timethatthedoorentrywasrecorded
            schemaFormat: application/vnd.apache.avro;version=1.9.0
    servers:
      gateway-group:
        url: >-
          my-eem-gateway-ibm-egw-rt-event-automation.apps.ocp-2700015rqr-y4lq.cloud.techzone.ibm.com:443
        protocol: kafka-secure
        security:
          - EGW-SECURITY: []
    components:
      securitySchemes:
        EGW-SECURITY:
          type: plain
    x-ibm-configuration:
      gateway: event-gateway
      type: asyncapi
      phase: realized
      enforced: true
      testable: false
      cors:
        enabled: false
      assembly:
        execute:
          - invoke-kafka:
              title: invoke-kafka
              version: 1.0.0
              clusterconfigid: 34937345-ac5e-4738-8788-80e462587db9
              bootstrap.servers: >-
                my-eem-gateway-ibm-egw-rt-event-automation.apps.ocp-2700015rqr-y4lq.cloud.techzone.ibm.com:443
      properties: {}
