apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: door-badgein-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: Door Badgein
      name: door-badgein-product
      description: >-
        Kafka Topic - Records an employee using their id badge to go through a door. This includes entry into the building overall, as well as entry through internal office doors. Building exits do not require use of id badge, so a door badge in event does not imply that the employee will still be in the building. Note that door events can take up to 3 minutes to reach the Kafka topic, so the badgetime value in the message payload should be treated as the canonical timestamp for the event. This delay can be inconsistent, so messages on the topic are often out of sequence as a result.
      version: '1.0'
    gateways:
       - event-gateway
    plans:
      default-plan:
        rate-limits:
          default:
            value: 100/1hour
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: door-badgein-api
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg
      catalog: sandbox
