apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cat-facts-api-cm
    files:
      - cat-facts-openapi.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:

  - cat-facts-api.yaml  
  - dog-facts-api.yaml  
  
  - countries-gql-api.yaml

  - door-badgein-api.yaml
  - sensor-readings-api.yaml

  - vehicle-info-api.yaml
  - vehicle-info-api-all-makes.yaml
  
  - mq-queue-api.yaml
  - mq-topic-api.yaml

  - rabbitmq-queue-api.yaml

  - products

patches:
  - target:
      kind: API
    path: apic-creds.yaml
  - target:
      kind: Product
    path: apic-creds.yaml
