apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: mainframe-orders-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: Mainframe MQ Order Events 
      name: mainframe-orders-product
      description: >-
        Kafka Topic - Exposing mainframe MQ orders queue via a streaming queue
      version: '1.0'
    gateways:
       - event-gateway
    plans:
      default-plan:
        rate-limits:
          default:
            value: 100/1hour
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: mainframe-orders-api
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg
      catalog: sandbox
