apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: mainframe-orders-api
  namespace: cp4i
spec:
  definition:
    configMap: mainframe-orders-api-definition
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mainframe-orders-api-definition
  namespace: cp4i
data:
  data: |-
    asyncapi: 2.1.0
    info:
      title: MAINFRAME.ORDERS
      version: 1.0.0
      x-ibm-name: MAINFRAME.ORDERS
      contact:
        email: notprovided@email.com
    channels:
      MAINFRAME.ORDERS:
        bindings:
          kafka:
            partitions: 3
            replicas: 3
        subscribe:
          message:
            payload: {}
    servers:
      cluster:
        url: $(bootstrapServerAddress)
        protocol: kafka-secure
        security:
          - X-IBM-Client-Id: []
    components:
      securitySchemes:
        X-IBM-Client-Id:
          type: plain
    x-ibm-configuration:
      enforced: true
      phase: realized
      assembly:
        execute:
          - invoke-kafka:
              title: invoke-kafka
              version: 1.0.0
              bootstrap.servers: $(bootstrapServerAddress)
              clusterconfigid: eventstreams
      properties:
        bootstrapServerAddress:
          value: handled.by.eem
      type: asyncapi
      testable: false
      x-ibm-eem: eventstreams
      cors:
        enabled: false
