kind: ConfigMap
apiVersion: v1
metadata:
  name: mq-queue-api-definition
  namespace: cp4i
data:
  data: |-
    asyncapi: 2.0.0
    info:
      title: Create Order
      version: 1.0.0
      description: This MQ queue accepts requests to create orders.
    x-ibm-configuration:
      phase: realized
      enforced: false
      testable: false
      type: asyncapi
    tags: 
      - name: MQ
      - name: Queue
      - name: Not Enforced
    servers:
      development:
        url: ibmmq://qmgr-dev:1414/qm1/DEV.APP.SVRCONN
        protocol: ibmmq
        description: Development
        security:
          - X-IBM-Client-Id: []
        bindings:
          ibmmq: 
            groupId: PRODCLSTR1
            cipherSpec: ANY_TLS12_OR_HIGHER
            bindingVersion: 0.1.0
      production:
        url: ibmmq://qmgr-prod:1414/qm1/DEV.APP.SVRCONN
        protocol: ibmmq
        description: Production
        security:
          - X-IBM-Client-Id: []
        bindings:
          ibmmq: 
            groupId: PRODCLSTR1
            cipherSpec: ANY_TLS12_OR_HIGHER
            bindingVersion: 0.1.0
    channels:
      order/create:
        bindings:
          ibmmq:
            destinationType: queue
            queue:
              objectName: ORDERS_CREATE
            bindingVersion: 0.1.0
        publish:
          message:
            $ref: '#/components/messages/OrderCreate'
            bindings:
              ibmmq:
                type: jms
                description: JMS bytes message
                bindingVersion: 0.1.0
    components:
      messages:
        OrderCreate:
          payload:
            type: object
            properties:
              displayName:
                type: string
                description: Name of the user
              email:
                type: string
                format: email
                description: Email of the user
      securitySchemes:
        X-IBM-Client-Id:
          type: userPassword
---
apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: mq-queue-api
  namespace: cp4i
spec:
  definition:
    configMap: mq-queue-api-definition
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg