apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: rabbitmq-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: 6. RabbitMQ
      name: rabbit-mq-product
      description: >-
        An example of RabbitMQ asyncapi bindings. 
      version: '1.0'
      categories:
        - Domain/Accounts
        - Protocol/AMQP
    plans:
      default-plan:
        rate-limits:
          default:
            value: 100/1hour
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: rabbitmq-queue-api
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg
      catalog: sandbox