apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: sensor-readings-api
  namespace: cp4i
spec:
  definition:
    configMap: sensor-readings-api-definition
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg
