apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: vechicle-info-product
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      title: Vehicle Info
      name: vechicle-info-product
      description: >-
        NHTSA Product Information Catalog Vehicle Listing
      version: '1.0'
    plans:
      default-plan:
        rate-limits:
          default:
            value: 100/1hour
        title: Default Plan
        description: Default Plan
        approval: false
  apis:
    apis:
      - name: vehicle-info-api
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: providerorg
      catalog: api-marketplace