kind: ConfigMap
apiVersion: v1
metadata:
  name: vehicle-info-api-definition
  namespace: cp4i
data:
  data: |-
    swagger: '2.0'
    info:
      version: 1.0.0
      title: NHTSA Product Information Catalog Vehicle Listing
      x-ibm-name: nhtsa-product-information-catalog-vehicle-listing
    basePath: /vehicle-manufacturers
    x-ibm-configuration:
      properties:
        target-url:
          value: https://vpic.nhtsa.dot.gov/api/vehicles/getallmanufacturers?format=json
          description: URL of the proxy policy
          encoded: false
      cors:
        enabled: true
      type: rest
      phase: realized
      enforced: false
      testable: false
    paths:
      /:
        get:
          responses:
            '200':
              description: success
              schema:
                type: string
          consumes: []
          produces: []
        put:
          responses:
            '200':
              description: success
              schema:
                type: string
          consumes: []
          produces: []
        post:
          responses:
            '200':
              description: success
              schema:
                type: string
          consumes: []
          produces: []
        delete:
          responses:
            '200':
              description: success
              schema:
                type: string
          consumes: []
          produces: []
        head:
          responses:
            '200':
              description: success
              schema:
                type: string
          consumes: []
          produces: []
        patch:
          responses:
            '200':
              description: success
              schema:
                type: string
          consumes: []
          produces: []
    schemes:
      - https
